"""Train slide-level classifier across artificial-CAM score-design variants (R4.2).

Holds the fractal shapes and the real-data budget fixed, and sweeps the
confidence-score design of the artificial CAMs (positive-confidence floor,
noise level, score mode). Answers: are the gains robust to the score ranges,
and how much comes from the fractal spatial prior vs. injected class-confidence?

Fixed: real = 25 per class (the most data-scarce, most sensitive regime),
artificial = 150 per class, patch backbone = ResNet-50, slide backbone =
ResNet-50. Each variant is averaged over NUM_RUNS seeds.

Prereqs:
  - real CAMs:   local/feature_maps/baseline/resnet50/{organ}/25/{train,val,test}/{D,M,N}/
  - test/val from .../{organ}/140/...
  - variants generated by generate_artificial_feature_maps_sweep.py:
        local/feature_maps/artificial/{variant}/{D,M,N}/
"""
from src.utils_slide_classifier import train_slide_classifier, test_slide_classifier
from src.utils_feature_maps import FeatureMapDataset
from torch.utils.data import DataLoader
from pathlib import Path
import random
import torch
import torchvision
import numpy as np
import pandas as pd


RANDOM_SEED = 2024
CLASSES = ['D', 'M', 'N']
BACKBONE_NAME = 'resnet50'        # patch backbone (selects real feature-map dir)
BATCH_SIZE = 128
NUM_WORKERS = 4
NUM_EPOCHS = 50
LEARNING_RATE = 1e-3
NUM_RUNS = 3
ORGANS = ['stomach', 'colon']
REAL_PER_CLASS = 25
ARTIFICIAL_PER_CLASS = 150
DEVICE = 'cuda:0'

VARIANTS = [
    "fractals_baseline",
    "fractals_pos0.5", "fractals_pos0.6", "fractals_pos0.7", "fractals_pos0.9",
    "fractals_noise0.0", "fractals_noise0.05", "fractals_noise0.2",
    "fractals_constant", "fractals_random",
]


def load_split(organ, real_per_class, artificial_type, writer):
    real_dir = f"local/feature_maps/baseline/{BACKBONE_NAME}/{organ}/{real_per_class}"
    test_dir = f"local/feature_maps/baseline/{BACKBONE_NAME}/{organ}/140"
    art_dir = f"local/feature_maps/artificial/{artificial_type}"
    assert Path(real_dir).exists(), f"missing real dir: {real_dir}"
    assert Path(test_dir).exists(), f"missing test dir: {test_dir}"
    assert Path(art_dir).exists(), f"missing artificial dir: {art_dir}"

    train_real = [
        (label, str(f))
        for label, c in enumerate(sorted(CLASSES))
        for f in Path(f"{real_dir}/train/{c}").iterdir() if f.suffix == '.txt'
    ]
    art = [
        (label, str(f))
        for label, c in enumerate(sorted(CLASSES))
        for f in Path(f"{art_dir}/{c}").iterdir() if f.suffix == '.txt'
    ]
    test_maps = [
        (subset, label, str(f))
        for subset in ['val', 'test']
        for label, c in enumerate(sorted(CLASSES))
        for f in Path(f"{test_dir}/{subset}/{c}").iterdir() if f.suffix == '.txt'
    ]
    df_real = pd.DataFrame(train_real, columns=['label', 'data_path'])
    df_art = pd.DataFrame(art, columns=['label', 'data_path'])
    df_test = pd.DataFrame(test_maps, columns=['subset', 'label', 'data_path'])

    train_data = []
    for label, _ in enumerate(CLASSES):
        real_list = df_real.query(f"label=={label}")[['data_path', 'label']].values.tolist()
        if REAL_PER_CLASS < len(real_list):
            real_list = random.sample(real_list, REAL_PER_CLASS)
        train_data.extend(real_list)
        art_list = df_art.query(f"label=={label}")[['data_path', 'label']].values.tolist()
        if ARTIFICIAL_PER_CLASS < len(art_list):
            art_list = random.sample(art_list, ARTIFICIAL_PER_CLASS)
        train_data.extend(art_list)

    val_data = df_test.query("subset=='val'")[['data_path', 'label']].values.tolist()
    test_data = df_test.query("subset=='test'")[['data_path', 'label']].values.tolist()
    return train_data, val_data, test_data


def run_once(organ, artificial_type, writer):
    train_data, val_data, test_data = load_split(organ, REAL_PER_CLASS, artificial_type, writer)
    train_loader = DataLoader(FeatureMapDataset(train_data, is_train=True),
                              batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS)
    val_loader = DataLoader(FeatureMapDataset(val_data, is_train=False),
                            batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)
    test_loader = DataLoader(FeatureMapDataset(test_data, is_train=False),
                             batch_size=BATCH_SIZE, shuffle=False, num_workers=NUM_WORKERS)

    model = torchvision.models.resnet50(weights='ResNet50_Weights.DEFAULT')
    model.fc = torch.nn.Linear(model.fc.in_features, len(CLASSES))
    slide_model, _ = train_slide_classifier(
        model=model, train_loader=train_loader, val_loader=val_loader,
        num_epochs=NUM_EPOCHS, learning_rate=LEARNING_RATE, device=DEVICE, writer=writer)
    test_acc, test_auc, _ = test_slide_classifier(
        model=slide_model, test_loader=test_loader, classes=CLASSES, device=DEVICE)
    return test_acc, test_auc


if __name__ == '__main__':
    torch.manual_seed(RANDOM_SEED)
    np.random.seed(RANDOM_SEED)
    random.seed(RANDOM_SEED)
    torch.cuda.manual_seed(RANDOM_SEED)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    for organ in ORGANS:
        basedir = Path(f"logs/slide_level/{organ}/score_sweep")
        basedir.mkdir(parents=True, exist_ok=True)
        writer_file = basedir / f"{BACKBONE_NAME}.txt"
        print(f"[{organ}] log file: {writer_file}")

        # resume: skip variants already logged with a SUMMARY line
        done = set()
        if writer_file.exists():
            import re
            for m in re.finditer(r"VARIANT=(\S+).*?ACCURACY:", writer_file.read_text(), re.S):
                done.add(m.group(1))

        with open(writer_file, 'a') as writer:
            for variant in VARIANTS:
                if variant in done:
                    print(f"[skip] {organ} {variant} already done")
                    continue
                print('=' * 30, file=writer)
                print(f"VARIANT={variant} organ={organ} real={REAL_PER_CLASS} art={ARTIFICIAL_PER_CLASS}")
                print(f"VARIANT={variant} organ={organ} real={REAL_PER_CLASS} art={ARTIFICIAL_PER_CLASS}", file=writer)
                accs, aucs = [], []
                for run in range(NUM_RUNS):
                    print(f"  run {run}")
                    print(f"  run {run}", file=writer)
                    acc, auc = run_once(organ, variant, writer)
                    accs.append(acc); aucs.append(auc)
                acc_m, acc_s = np.mean(accs), np.std(accs)
                auc_m, auc_s = np.mean(aucs), np.std(aucs)
                summary = (f"{organ}. VARIANT={variant}. ACCURACY: {acc_m:.4f} +/- {acc_s:.4f}. "
                           f"AUC: {auc_m:.4f} +/- {auc_s:.4f}")
                print(summary)
                print(summary + "\n", file=writer)
